import { Injectable } from '@angular/core';
import { Food } from '../../shared/models/Food';

@Injectable({
  providedIn: 'root',
})
export class FoodService {
  constructor() {}

  getAll(): Food[] {
    return [
      {
        id: 1,
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 10,
        favorite: true,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: '/assets/Images/food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id: 2,
        name: 'Meatball',
        price: 20,
        cookTime: '20-30',
        favorite: true,
        origins: ['middle east'],
        stars: 4.7,
        imageUrl: '/assets/Images/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
      },
      {
        id: 3,
        name: 'Hamburger',
        price: 5,
        cookTime: '10-15',
        favorite: false,
        origins: ['usa'],
        stars: 3.5,
        imageUrl: '/assets/Images/food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
      },
      {
        id: 4,
        name: 'Fried Potatoes',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium'],
        stars: 3.3,
        imageUrl: '/assets/Images/food-4.jpg',
        tags: ['FastFood', 'Fry'],
      },
      {
        id: 5,
        name: 'Chicken Soup',
        price: 11,
        cookTime: '40-50',
        favorite: false,
        origins: ['asia'],
        stars: 3.0,
        imageUrl: '/assets/Images/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
      },
      {
        id: 6,
        name: 'Sushi',
        price: 8,
        cookTime: '20-30',
        favorite: false,
        origins: ['japan'],
        stars: 4.0,
        imageUrl: '/assets/Images/food-7.jpg',
        tags: ['FastFood', 'Sushi', 'Lunch'],
      },
      {
        id: 7,
        name: 'Biryani',
        price: 10,
        cookTime: '40-50',
        favorite: true,
        origins: ['india'],
        stars: 5.0,
        imageUrl: '/assets/Images/food-10.jpg',
        tags: ['FastFood', 'Biryani', 'Lunch'],
      },
      {
        id: 8,
        name: 'Steak',
        price: 20,
        cookTime: '30-40',
        favorite: false,
        origins: ['usa'],
        stars: 5.0,
        imageUrl: '/assets/Images/food-15.jpg',
        tags: ['FastFood', 'steak', 'Lunch'],
      },
      {
        id: 9,
        name: 'Croissant ',
        price: 6,
        cookTime: '10-20',
        favorite: true,  
        origins: ['france'],
        stars: 4.0,
        imageUrl: '/assets/Images/food-8.jpg',
        tags: ['FastFood', 'Croissant', 'Lunch'],
      },
      {
        id: 10,
        name: 'Poutine',
        price: 8,
        cookTime: '10-20',
        favorite: false,
        origins: ['canada'],
        stars: 3.0,
        imageUrl: '/assets/Images/food-11.jpg',
        tags: ['FastFood', 'Poutine', 'Lunch'],
      },
      {
        id: 11,
        name: 'Shawarma',
        price: 11,
        cookTime: '10-20',
        favorite: true,
        origins: ['lebanon'],
        stars: 5.0,
        imageUrl: '/assets/Images/food-13.jpg',
        tags: ['FastFood', 'Shawarma', 'Lunch'],
      },
      {
        id: 12,
        name: 'Ramen',
        price: 9,
        cookTime: '10-20',
        favorite: false,
        origins: ['japan'],
        stars: 4.0,
        imageUrl: '/assets/Images/food-12.jpg',
        tags: ['FastFood', 'Ramen', 'Lunch'],
      },
      {
        id: 13,
        name: 'Tacos',
        price: 7,
        cookTime: '5-10',
        favorite: true,
        origins: ['mexico'],
        stars: 3.0,
        imageUrl: '/assets/Images/food-9.jpg',
        tags: ['FastFood', 'Tacos', 'Lunch'],
      },
    ];
  }
}
